add sign schema file
GSG-G11/Blog-Post pull request #40
Opened 2022-03-08 21:59 UTC by yousrakhaleel

Relates #11

2022-03-08 22:28 UTC, Mohammed-Hamada requested changes
password validation should be thing like this:
```js
password: Joi.string().pattern(/^[a-zA-Z0-9]{3,30}$/),
```

2022-03-09 06:21 UTC, zaher-aa requested changes
Great job, but where is the signup controller??

2022-03-09 06:21 UTC, zaher-aa commented on server/utils/hashPassword.js
> +module.exports = hashPassword;
Try to use a promise instead of a callback

2022-03-09 08:47 UTC, Mohammed-Hamada approved these changes

2022-03-09 09:25 UTC, zaher-aa approved these changes

2022-03-09 09:25 UTC, merged